#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb  9 14:02:32 2023

@author: intern
"""

def gofile()
Img1_dir = '/home/intern/下載/old data/real_PPE-data/train/labels'

annotations = os.listdir(Img1_dir)
i = 0
%cd /home/intern/下載/old data/real_PPE-data/train/labels